### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by lossycrypt** [emptyrivers/ProductionChain#1]
1) Pressing the [PC] Button in a new game brings up a frame that only contains a ? button that prints a meaningless message.
2) Pressing ALT+G (after looking it up) does not have any observable effect.
3) Trying to load an existing game instantly errors:
Error while running event production_chain::on_tick (ID 0) __pdorction_chain__/modules/DataStructures.lua:118: attempt to index field 'techTree' (a nil value)

And the mod portal is lacking pictures.

**Comment by ShadesOfHue** [comment]
Loading this mod onto my Angels+Bobs+Yuoki game results in the above error. 
Specifically:
Error while running event productions_chain::on_tick{ID 0}
_ _ production_chain_ _ /modules/DataStructures.lua:118:attempt to index field'techTree'(a nil value)

**Comment by emptyrivers** [comment]
Uploading a new version later this week.
